name: group_kiosk
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2

  cupertino_icons: ^1.0.8
  firebase_core: ^4.9.0
  firebase_storage: ^13.4.1
  cloud_firestore: ^6.4.1
  firebase_auth: ^6.5.1
  firebase_database: ^12.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/mg.jpeg
    - assets/images/milo_ice.jpeg
    - assets/images/nasi_kerabu.jpeg
    - assets/images/nasi_kukus_ayam.jpg
    - assets/images/nasi_lemak.jpeg
    - assets/images/ngk.jpg
    - assets/images/sky_juice.jpg
    - assets/images/TEH_AIS.png
    - assets/images/teh_o.jpg
    - assets/images/teh_tarik.jpg