// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgSRPNo4BpNDKy8pUd0EJ4cmMJSqrt4wc',
    appId: '1:238806264153:web:21584e22c014be10d58448',
    messagingSenderId: '238806264153',
    projectId: 'group-kiosk',
    authDomain: 'group-kiosk.firebaseapp.com',
    databaseURL: 'https://group-kiosk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'group-kiosk.firebasestorage.app',
    measurementId: 'G-G03F8GV6LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZZZT6wVai5JpmuuK9HDJaMN97qy1GJus',
    appId: '1:238806264153:android:d051efdc7822174ad58448',
    messagingSenderId: '238806264153',
    projectId: 'group-kiosk',
    databaseURL: 'https://group-kiosk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'group-kiosk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Kil9VvskVa02dywA4VN1Zw12h95QoNs',
    appId: '1:238806264153:ios:da264f5fb0b33a99d58448',
    messagingSenderId: '238806264153',
    projectId: 'group-kiosk',
    databaseURL: 'https://group-kiosk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'group-kiosk.firebasestorage.app',
    iosBundleId: 'com.example.groupKiosk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Kil9VvskVa02dywA4VN1Zw12h95QoNs',
    appId: '1:238806264153:ios:da264f5fb0b33a99d58448',
    messagingSenderId: '238806264153',
    projectId: 'group-kiosk',
    databaseURL: 'https://group-kiosk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'group-kiosk.firebasestorage.app',
    iosBundleId: 'com.example.groupKiosk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgSRPNo4BpNDKy8pUd0EJ4cmMJSqrt4wc',
    appId: '1:238806264153:web:eabeaec186fa8087d58448',
    messagingSenderId: '238806264153',
    projectId: 'group-kiosk',
    authDomain: 'group-kiosk.firebaseapp.com',
    databaseURL: 'https://group-kiosk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'group-kiosk.firebasestorage.app',
    measurementId: 'G-XPG1RFVJRB',
  );
}
